server:
  http2:
    enabled: true
  compression:
    enabled: true
  port: 18011
spring:
  application:
    name: kele-miaosha

  datasource:
    url: jdbc:mysql://localhost:3306/dev?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: xukele
    password: kele1234

  redis:
    host: localhost
    password: 0192023a7bbd73250516f069df18b500
    database: 3
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
